# Generated by Django 5.0.3 on 2024-03-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivinglicense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglicense',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='drivinglicense',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='drivinglicense',
            name='middle_name',
        ),
    ]
