# Generated by Django 5.0.3 on 2024-03-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivinglicense', '0002_rename_first_name_drivinglicense_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglicense',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
