# Generated by Django 5.0.3 on 2024-03-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                help_text="Required. 10 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=15,
                verbose_name="phone_number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="user",
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=50,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
