# Generated by Django 5.0.3 on 2024-03-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle", "0002_alter_vehicle_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="OilService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fill_date", models.DateField(blank=True, null=True)),
                (
                    "next_service_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expire_date", models.DateField(blank=True, null=True)),
                ("notification_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oil_services",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
        ),
    ]
