# Generated by Django 5.0.3 on 2024-03-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0002_alter_vehicle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('notification_status', models.BooleanField(default=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='fullinsurances/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_insurances', to='vehicle.vehicle')),
            ],
        ),
    ]
