# Generated by Django 5.0.3 on 2024-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullinsurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullinsurance',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
