# Generated by Django 5.0.3 on 2024-03-24 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadfund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadfund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadfund',
            name='notification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roadfund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roadfund',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roadfunds/'),
        ),
    ]
